(() => {
    const REGION_FILTERS = Object.freeze([
        { key: "all", label: "All", messageKey: "regionFilterAll" },
        { key: "Asia_Pacific", label: "Asia Pacific", messageKey: "regionFilterAsiaPacific" },
        { key: "USA_Canada", label: "USA/Canada", messageKey: "regionFilterUsaCanada" },
        { key: "Europe", label: "Europe", messageKey: "regionFilterEurope" },
        { key: "LatinAmerica_Caribbean", label: "Latin America/Caribbean", messageKey: "regionFilterLatinAmericaCaribbean" },
        { key: "Africa_MiddleEast_India", label: "Africa/Middle East/India", messageKey: "regionFilterAfricaMiddleEastIndia" }
    ]);

    const COMMON_REGION_CODES = Object.freeze(["cn","hk","jp","us","ca","tw","kr","sg","my","th","id","ph","vn","in","au","nz","gb","de","fr","it","es","nl","se","no","dk","fi","br","mx","ar","cl","tr","ae","sa","il"]);

    const ALL_REGIONS = Object.freeze([
        ["cn","🇨🇳","China","Asia_Pacific"],
        ["jp","🇯🇵","Japan","Asia_Pacific"],
        ["hk","🇭🇰","Hongkong","Asia_Pacific"],
        ["tw","🇹🇼","Taiwan","Asia_Pacific"],
        ["kr","🇰🇷","Korea","Asia_Pacific"],
        ["ae","🇦🇪","The United Arab Emirates","Africa_MiddleEast_India"],
        ["om","🇴🇲","Oman","Africa_MiddleEast_India"],
        ["az","🇦🇿","Azerbaijan","Europe"],
        ["pk","🇵🇰","Pakistan","Asia_Pacific"],
        ["bh","🇧🇭","Bahrain","Africa_MiddleEast_India"],
        ["bt","🇧🇹","Bhutan","Asia_Pacific"],
        ["ph","🇵🇭","Philippines","Asia_Pacific"],
        ["us","🇺🇸","United States","USA_Canada"],
        ["ca","🇨🇦","Canada","USA_Canada"],
        ["br","🇧🇷","Brazil","LatinAmerica_Caribbean"],
        ["ar","🇦🇷","Argentina","LatinAmerica_Caribbean"],
        ["sg","🇸🇬","Singapore","Asia_Pacific"],
        ["kz","🇰🇿","Kazakhstan","Asia_Pacific"],
        ["kg","🇰🇬","Kyrgyzstan","Asia_Pacific"],
        ["kh","🇰🇭","Cambodia","Asia_Pacific"],
        ["qa","🇶🇦","Qatar","Africa_MiddleEast_India"],
        ["kw","🇰🇼","Kuwait","Africa_MiddleEast_India"],
        ["la","🇱🇦","Laos","Asia_Pacific"],
        ["lb","🇱🇧","Lebanon","Africa_MiddleEast_India"],
        ["my","🇲🇾","Malaysia","Asia_Pacific"],
        ["mn","🇲🇳","Mongolia","Asia_Pacific"],
        ["np","🇳🇵","Nepal","Asia_Pacific"],
        ["sa","🇸🇦","Saudi Arabia","Africa_MiddleEast_India"],
        ["lk","🇱🇰","Sri Lanka","Asia_Pacific"],
        ["tj","🇹🇯","Tajikstan","Asia_Pacific"],
        ["th","🇹🇭","Thailand","Asia_Pacific"],
        ["tr","🇹🇷","Turkey","Europe"],
        ["tm","🇹🇲","Turkmenistan","Asia_Pacific"],
        ["bn","🇧🇳","Brunei","Asia_Pacific"],
        ["uz","🇺🇿","Uzbekistan","Asia_Pacific"],
        ["mo","🇲🇴","Macao","Asia_Pacific"],
        ["am","🇦🇲","Armenia","Africa_MiddleEast_India"],
        ["ye","🇾🇪","Yemen","Africa_MiddleEast_India"],
        ["il","🇮🇱","Israel","Asia_Pacific"],
        ["in","🇮🇳","India","Africa_MiddleEast_India"],
        ["id","🇮🇩","Indonesia","Asia_Pacific"],
        ["jo","🇯🇴","Jordan","Africa_MiddleEast_India"],
        ["vn","🇻🇳","Vietnam","Asia_Pacific"],
        ["al","🇦🇱","Albania","Europe"],
        ["ie","🇮🇪","Ireland","Europe"],
        ["ee","🇪🇪","Estonia","Europe"],
        ["at","🇦🇹","Austria","Europe"],
        ["by","🇧🇾","Belarus","Europe"],
        ["bg","🇧🇬","Bulgaria","Europe"],
        ["mk","🇲🇰","North Macedonia","Europe"],
        ["be","🇧🇪","Belgium","Europe"],
        ["is","🇮🇸","Iceland","Europe"],
        ["pl","🇵🇱","Poland","Europe"],
        ["dk","🇩🇰","Denmark","Europe"],
        ["de","🇩🇪","Germany","Europe"],
        ["ru","🇷🇺","Russia","Europe"],
        ["fr","🇫🇷","France","Europe"],
        ["fi","🇫🇮","Finland","Europe"],
        ["nl","🇳🇱","Netherlands","Europe"],
        ["cz","🇨🇿","Czech Republic","Europe"],
        ["hr","🇭🇷","Croatia","Europe"],
        ["lv","🇱🇻","Latvia","Europe"],
        ["lt","🇱🇹","Lithuania","Europe"],
        ["lu","🇱🇺","Luxembourg","Europe"],
        ["ro","🇷🇴","Romania","Europe"],
        ["mt","🇲🇹","Malta","Europe"],
        ["md","🇲🇩","Moldova","Europe"],
        ["no","🇳🇴","Norway","Europe"],
        ["pt","🇵🇹","Portugal","Europe"],
        ["se","🇸🇪","Sweden","Europe"],
        ["ch","🇨🇭","Switzerland","Europe"],
        ["sl","🇸🇱","Sierra Leone","Africa_MiddleEast_India"],
        ["sk","🇸🇰","Slovakia","Europe"],
        ["si","🇸🇮","Slovenia","Europe"],
        ["ua","🇺🇦","Ukraine","Europe"],
        ["es","🇪🇸","Spain","Europe"],
        ["gr","🇬🇷","Greece","Europe"],
        ["hu","🇭🇺","Hungary","Europe"],
        ["it","🇮🇹","Italy","Europe"],
        ["gb","🇬🇧","United Kingdom","Europe"],
        ["ai","🇦🇮","Anguilla","LatinAmerica_Caribbean"],
        ["ag","🇦🇬","Antigua and Barbuda","LatinAmerica_Caribbean"],
        ["bb","🇧🇧","Barbados","LatinAmerica_Caribbean"],
        ["bs","🇧🇸","Bahamas","LatinAmerica_Caribbean"],
        ["pa","🇵🇦","Panama","LatinAmerica_Caribbean"],
        ["bm","🇧🇲","Bermuda","LatinAmerica_Caribbean"],
        ["bz","🇧🇿","Belize","LatinAmerica_Caribbean"],
        ["do","🇩🇴","Dominican Republic","LatinAmerica_Caribbean"],
        ["dm","🇩🇲","Dominica","LatinAmerica_Caribbean"],
        ["cr","🇨🇷","Costa Rica","LatinAmerica_Caribbean"],
        ["gd","🇬🇩","Grenada","LatinAmerica_Caribbean"],
        ["hn","🇭🇳","Honduras","LatinAmerica_Caribbean"],
        ["ky","🇰🇾","Cayman Islands","LatinAmerica_Caribbean"],
        ["ms","🇲🇸","Montserrat","LatinAmerica_Caribbean"],
        ["mx","🇲🇽","Mexico","LatinAmerica_Caribbean"],
        ["ni","🇳🇮","Nicaragua","LatinAmerica_Caribbean"],
        ["sv","🇸🇻","El Salvador","LatinAmerica_Caribbean"],
        ["kn","🇰🇳","St. Kitts and Nevis","LatinAmerica_Caribbean"],
        ["lc","🇱🇨","St. Lucia","LatinAmerica_Caribbean"],
        ["vc","🇻🇨","St. Vincent and the Grenadines","LatinAmerica_Caribbean"],
        ["tc","🇹🇨","Turks and Caicos Islands","LatinAmerica_Caribbean"],
        ["tt","🇹🇹","Trinidad and Tobago","LatinAmerica_Caribbean"],
        ["gt","🇬🇹","Guatemala","LatinAmerica_Caribbean"],
        ["jm","🇯🇲","Jamaica","LatinAmerica_Caribbean"],
        ["vg","🇻🇬","British Virgin Islands","LatinAmerica_Caribbean"],
        ["py","🇵🇾","Paraguay","LatinAmerica_Caribbean"],
        ["bo","🇧🇴","Bolivia","LatinAmerica_Caribbean"],
        ["ec","🇪🇨","Ecuador","LatinAmerica_Caribbean"],
        ["co","🇨🇴","Colombia","LatinAmerica_Caribbean"],
        ["gy","🇬🇾","Guyana","LatinAmerica_Caribbean"],
        ["pe","🇵🇪","Peru","LatinAmerica_Caribbean"],
        ["sr","🇸🇷","Suriname","LatinAmerica_Caribbean"],
        ["ve","🇻🇪","Venezuela","LatinAmerica_Caribbean"],
        ["uy","🇺🇾","Uruguay","LatinAmerica_Caribbean"],
        ["cl","🇨🇱","Chile","LatinAmerica_Caribbean"],
        ["au","🇦🇺","Australia","Asia_Pacific"],
        ["pg","🇵🇬","Papua New Guinea","Asia_Pacific"],
        ["fj","🇫🇯","Fiji","Asia_Pacific"],
        ["fm","🇫🇲","Micronesia","Asia_Pacific"],
        ["pw","🇵🇼","Palau","Asia_Pacific"],
        ["sb","🇸🇧","Solomon Islands","Asia_Pacific"],
        ["nz","🇳🇿","New Zealand","Asia_Pacific"],
        ["dz","🇩🇿","Algeria","Africa_MiddleEast_India"],
        ["eg","🇪🇬","Egypt","Africa_MiddleEast_India"],
        ["ao","🇦🇴","Angola","Africa_MiddleEast_India"],
        ["bj","🇧🇯","Benin","Africa_MiddleEast_India"],
        ["bw","🇧🇼","Botswana","Africa_MiddleEast_India"],
        ["bf","🇧🇫","Burkina Faso","Africa_MiddleEast_India"],
        ["cv","🇨🇻","Cape Verde","Africa_MiddleEast_India"],
        ["gm","🇬🇲","Gambia","Africa_MiddleEast_India"],
        ["cg","🇨🇬","Congo, Republic of the","Africa_MiddleEast_India"],
        ["gw","🇬🇼","Guinea-Bissau","Africa_MiddleEast_India"],
        ["gh","🇬🇭","Ghana","Africa_MiddleEast_India"],
        ["zw","🇿🇼","Zimbabwe","Africa_MiddleEast_India"],
        ["ke","🇰🇪","Kenya","Africa_MiddleEast_India"],
        ["lr","🇱🇷","Liberia","Africa_MiddleEast_India"],
        ["mg","🇲🇬","Madagascar","Africa_MiddleEast_India"],
        ["mw","🇲🇼","Malawi","Africa_MiddleEast_India"],
        ["ml","🇲🇱","Mali","Africa_MiddleEast_India"],
        ["mu","🇲🇺","Mauritius","Africa_MiddleEast_India"],
        ["mr","🇲🇷","Mauritania","Africa_MiddleEast_India"],
        ["mz","🇲🇿","Mozambique","Africa_MiddleEast_India"],
        ["na","🇳🇦","Namibia","Africa_MiddleEast_India"],
        ["za","🇿🇦","South Africa","Africa_MiddleEast_India"],
        ["ne","🇳🇪","Niger","Africa_MiddleEast_India"],
        ["ng","🇳🇬","Nigeria","Africa_MiddleEast_India"],
        ["sn","🇸🇳","Senegal","Africa_MiddleEast_India"],
        ["cy","🇨🇾","Cyprus","Europe"],
        ["sc","🇸🇨","Seychelles","Africa_MiddleEast_India"],
        ["st","🇸🇹","Sao Tome and Principe","Africa_MiddleEast_India"],
        ["sz","🇸🇿","Eswatini","Africa_MiddleEast_India"],
        ["tz","🇹🇿","Tanzania","Africa_MiddleEast_India"],
        ["tn","🇹🇳","Tunisia","Africa_MiddleEast_India"],
        ["ug","🇺🇬","Uganda","Africa_MiddleEast_India"],
        ["td","🇹🇩","Chad","Africa_MiddleEast_India"],
        ["cd","🇨🇩","Congo, Democratic Republic of the","Africa_MiddleEast_India"],
        ["af","🇦🇫","Afghanistan","Africa_MiddleEast_India"],
        ["ba","🇧🇦","Bosnia and Herzegovina","Europe"],
        ["cm","🇨🇲","Cameroon","Africa_MiddleEast_India"],
        ["ga","🇬🇦","Gabon","Africa_MiddleEast_India"],
        ["gf","🇬🇫","French Guiana","Africa_MiddleEast_India"],
        ["iq","🇮🇶","Iraq","Africa_MiddleEast_India"],
        ["xk","🇽🇰","Kosovo","Europe"],
        ["ly","🇱🇾","Libya","Africa_MiddleEast_India"],
        ["me","🇲🇪","Montenegro","Europe"],
        ["ma","🇲🇦","Morocco","Africa_MiddleEast_India"],
        ["mm","🇲🇲","Myanmar","Asia_Pacific"],
        ["nr","🇳🇷","Nauru","Asia_Pacific"],
        ["rw","🇷🇼","Rwanda","Africa_MiddleEast_India"],
        ["rs","🇷🇸","Serbia","Europe"],
        ["to","🇹🇴","Tonga","Asia_Pacific"],
        ["vu","🇻🇺","Vanuatu","Asia_Pacific"],
        ["zm","🇿🇲","Zambia","Africa_MiddleEast_India"],
        ["bd","🇧🇩","Bangladesh","Asia_Pacific"],
        ["ci","🇨🇮","Côte d'Ivoire","Africa_MiddleEast_India"],
        ["li","🇱🇮","Liechtenstein","Europe"],
        ["mv","🇲🇻","Maldives","Asia_Pacific"],
        ["kp","🇰🇵","Korea","Asia_Pacific"],
    ].map(([code, flag, name, group]) => Object.freeze({ code, flag, name, group })));

    const REGION_CODES = Object.freeze(ALL_REGIONS.map((region) => region.code));

    const REGION_BY_CODE = Object.freeze(ALL_REGIONS.reduce((regionsByCode, region) => {
        regionsByCode[region.code] = region;
        return regionsByCode;
    }, {}));

    globalThis.StoreFixRegions = Object.freeze({
        ALL_REGIONS,
        COMMON_REGION_CODES,
        REGION_BY_CODE,
        REGION_CODES,
        REGION_FILTERS
    });
})();
